title: TSRoom

resources:
  - url: /local/custom_ui/bar-card.js?v=1.0.0
    type: js
  - url: /local/custom_ui/mini-graph-card-bundle.js
    type: module
  - url: /local/custom_ui/vertical-stack-in-card.js?v=0.1.2
    type: js
  - url: /local/custom_ui/dark-sky-weather-card.js?
    type: module
  - url: /local/custom_ui/air-visual-card.js
    type: js

background: center / cover no-repeat url("/local/lovelace/background_19.png") fixed
views:

#############################################################################################################################################
#                                                                                                                                           # 
#                                                               DEMO VIEW                                                              #
#                                                                                                                                           #
#############################################################################################################################################
  - badges:
      - person.thuanzero94
      - sun.sun
      - sensor.moon
    cards:
      - entity: weather.tuson
        type: weather-forecast
    path: default_view
    title: lovelace_test

#############################################################################################################################################
#                                                                                                                                           # 
#                                                               VIEW 0 - HOME                                                               #
#                                                                                                                                           #
#############################################################################################################################################
  - id: 0
    icon: mdi:castle
    name: Home
    cards:

#################################################################
#                                                               #
#                      Home - Weather Card                      #
#                                                               #
#################################################################
      - type: vertical-stack
        cards:
          - type: 'custom:dark-sky-weather-card'
            entity_current_conditions: sensor.dark_sky_icon
            entity_temperature: sensor.dark_sky_temperature
            entity_forecast_high_temp_1: sensor.dark_sky_daytime_high_temperature_1d
            entity_forecast_high_temp_2: sensor.dark_sky_daytime_high_temperature_2d
            entity_forecast_high_temp_3: sensor.dark_sky_daytime_high_temperature_3d
            entity_forecast_high_temp_4: sensor.dark_sky_daytime_high_temperature_4d
            entity_forecast_high_temp_5: sensor.dark_sky_daytime_high_temperature_5d
            entity_forecast_icon_1: sensor.dark_sky_icon_1d
            entity_forecast_icon_2: sensor.dark_sky_icon_2d
            entity_forecast_icon_3: sensor.dark_sky_icon_3d
            entity_forecast_icon_4: sensor.dark_sky_icon_4d
            entity_forecast_icon_5: sensor.dark_sky_icon_5d
            entity_forecast_low_temp_1: sensor.dark_sky_overnight_low_temperature_0d
            entity_forecast_low_temp_2: sensor.dark_sky_overnight_low_temperature_1d
            entity_forecast_low_temp_3: sensor.dark_sky_overnight_low_temperature_2d
            entity_forecast_low_temp_4: sensor.dark_sky_overnight_low_temperature_3d
            entity_forecast_low_temp_5: sensor.dark_sky_overnight_low_temperature_4d
            entity_summary_1: sensor.dark_sky_summary_1d
            entity_summary_2: sensor.dark_sky_summary_2d
            entity_summary_3: sensor.dark_sky_summary_3d
            entity_summary_4: sensor.dark_sky_summary_4d
            entity_summary_5: sensor.dark_sky_summary_5d

            entity_sun: sun.sun
            entity_visibility: sensor.dark_sky_visibility
            entity_daytime_high: sensor.dark_sky_daytime_high_temperature_0d
            entity_wind_bearing: sensor.dark_sky_wind_bearing
            entity_wind_speed: sensor.dark_sky_wind_speed
            entity_humidity: sensor.dark_sky_humidity
            entity_pressure: sensor.dark_sky_pressure
            entity_apparent_temp: sensor.dark_sky_apparent_temperature
            entity_daily_summary: sensor.dark_sky_daily_summary
            entity_pop: sensor.dark_sky_precip_probability
            entity_pop_intensity: sensor.dark_sky_precip_intensity
            entity_pop_1: sensor.dark_sky_precip_probability_1d
            entity_pop_2: sensor.dark_sky_precip_probability_2d
            entity_pop_3: sensor.dark_sky_precip_probability_3d
            entity_pop_4: sensor.dark_sky_precip_probability_4d
            entity_pop_5: sensor.dark_sky_precip_probability_5d

            # entity_current_text: sensor.dark_sky_current_text
            # alt_daytime_high: sensor.dark_sky_alt_daytime_high 
            # alt_wind: sensor.dark_sky_alt_wind
            # alt_visibility: sensor.dark_sky_alt_visibility
            # alt_pop: sensor.dark_sky_alt_pop
            # alt_pressure: sensor.dark_sky_alt_pressure
            # alt_humidity: sensor.dark_sky_alt_humidity
            locale: en
            static_icons: false
            tooltip_bg_color: 'rgb( 75,155,239)'
            tooltip_border_color: orange
            tooltip_border_width: 3
            tooltip_caret_size: 10
            tooltip_fg_color: '#fff'
            tooltip_left_offset: -12
            tooltip_width: 100
            tooltips: true
            old_daily_format: false
            time_format: 24
            show_beaufort: true

#################################################################
#                                                               #
#                    Home - Air Quality Card                    #
#                                                               #
#################################################################
          - type: "custom:air-visual-card"
            # icons: /local/icons/aqi_icons
            air_pollution_level: sensor.u_s_air_pollution_level_3
            air_quality_index: sensor.u_s_air_quality_index_3
            main_pollutant: sensor.u_s_main_pollutant_3
            temp: weather.dark_sky
            city: 'Vinh Yen'

#############################################################################################################################################
#                                                                                                                                           # 
#                                                          VIEW 1 - SYSTEM STATUS                                                          #
#                                                                                                                                           #
#############################################################################################################################################

  - id: 1  
    icon: mdi:settings
    name: System Status
    cards:

#################################################################
#                                                               #
#                  System Status - Internet Card                #
#                                                               #
#################################################################

      - type: vertical-stack
        cards:
          - type: horizontal-stack
            cards:
              - type: custom:bar-card
                title_position: inside
                show_icon: true
                align: split
                padding: 4px
                card_style: 
                  border-radius: 5px
                columns: 1
                max: 100
                entities:
                  - entity: sensor.speedtest_ping
                    severity:
                    - value: 20
                      color: '#1db954'
                    - value: 30
                      color: '#bf9540'
                    - value: 50
                      color: '#bf4040'       
          - type: horizontal-stack
            cards:
              - type: custom:mini-graph-card
                entities: 
                  - sensor.speedtest_download
                height: 50
                line_width: 2
                font_size: 70
                hours_to_show: 168
                points_per_hour: 1
                show:
                  extrema: true
                  fill: true
                color_thresholds:
                  - value: 0
                    color: "#FFFF00"
                  - value: 40
                    color: "#3498db"
                    
              - type: custom:mini-graph-card
                entities: 
                  - sensor.speedtest_upload
                height: 50
                line_width: 2
                font_size: 70
                hours_to_show: 168
                points_per_hour: 1
                show:
                  extrema: true
                  fill: true
                color_thresholds:
                  - value: 0
                    color: "#FFFF00"
                  - value: 13
                    color: "#3498db"

#################################################################
#                                                               #
#               System Status - NUC Resources Card              #
#                                                               #
#################################################################

      - type: vertical-stack
        cards:    
          - type: entities
            show_header_toggle: off
            entities:
              - type: section
                label: HASSIO SERVER ---- Raspberry pi 3B+ ---- Raspbian OS---- HA 0.99.2
              - type: custom:vertical-stack-in-card
                cards:
                  - type: horizontal-stack
                    cards:
                      # - type: vertical-stack
                      #   cards:
                      #     - type: custom:card-modder
                      #       card: 
                      #         type: picture
                      #         image: /local/lovelace/settings/rpi.png
                      #       style:                 
                      #         border-radius: 5px
                     
                      # - type: custom:bar-card
                      #   title_position: inside
                      #   entity: sensor.ha_restart_time
                      #   title: Restart Time
                      #   align: center
                      #   padding: 5px
                      #   max: 60
                      #   card_style: 
                      #     border-radius: 5px
                      - type: custom:bar-card
                        title_position: inside
                        entity: sensor.time_online
                        title: Up Time this Week
                        align: center
                        padding: 5px
                        max: 168
                        card_style: 
                          border-radius: 5px
                      - type:  custom:bar-card
                        title_position: inside
                        entity: sensor.last_boot
                        title: Last boot time
                        align: center
                        padding: 5px
                        max: 168
                        card_style:
                          border-radius: 5px
           
              - type: custom:bar-card
                align: split
                show_icon: true
                padding: 4px
                columns: 2
                card_style: 
                  border-radius: 5px
                entities:
                  - entity: sensor.disk_use_percent
                    title: Disk
                  - entity: sensor.memory_use_percent
                    title: RAM

              - type: custom:bar-card
                align: split
                show_icon: true
                padding: 4px
                columns: 2
                card_style: 
                  border-radius: 5px
                entities:
                  - entity: sensor.processor_use
                    title: CPU
                  - entity: sensor.cpu_temperature
                    title: Temp  
                    icon: mdi:thermometer

              - type: custom:bar-card
                align: split
                show_icon: true
                padding: 4px
                columns: 2
                card_style: 
                  border-radius: 5px
                entities:
                  - entity: sensor.network_throughput_in_eth0
                    title: Net In
                    icon: mdi:download-network-outline
                  - entity: sensor.network_throughput_out_eth0
                    title: Net Out  
                    icon: mdi:upload-network-outline