#################################################################
#                                                               #
#                    Packages/Core Network                      #
#                                                               #
#################################################################

#################################################################
#                                                               #
#                          Customize                            #
#                                                               #
#################################################################
homeassistant:
  customize:
    sensor.disk_use:
      friendly_name: Disk Use
    sensor.speedtest_ping:
      friendly_name: Ping
      icon: mdi:pulse
    sensor.speedtest_download:
      friendly_name: Download
      icon: mdi:arrow-down-bold
    sensor.speedtest_upload:
      friendly_name: Upload
      icon: mdi:arrow-up-bold


#################################################################
#                                                               #
#                       Device Tracker                          #
#                                                               #
#################################################################
device_tracker:

####################################################
#                                                  #
#               Device Track - Ping                #
#                                                  #
####################################################
  - platform: ping
    hosts:
      work_pc: !secret work_pc


#################################################################
#                                                               #
#                           Sensors                             #
#                                                               #
#################################################################
sensor:
####################################################
#                                                  #
#              Sensor - Command Line               #
#                                                  #
####################################################

  - platform: command_line
    name: CPU Temperature
    command: "cat /sys/class/thermal/thermal_zone0/temp"
    unit_of_measurement: "°C"
    value_template: '{{ (value | multiply(0.001)) | round(1) }}'

####################################################
#                                                  #
#                Sensor - File Size                #
#                                                  #
####################################################

  # - platform: filesize
  #   file_paths:
  #     - /home/builder/.homeassistant/home-assistant_v2.db
  #     - /home/builder/.homeassistant/home-assistant.log

####################################################
#                                                  #
#             Sensor - System Monitor              #
#                                                  #
####################################################

  - platform: systemmonitor
    resources:
    - type: disk_use_percent
      arg: '/'
    - type: memory_use_percent
    - type: processor_use
    - type: last_boot
    - type: throughput_network_in
      arg: eth0
    - type: throughput_network_out
      arg: eth0

####################################################
#                                                  #
#                 Sensor - Uptime                  #
#                                                  #
####################################################

  - platform: uptime
    name: Time Online
    unit_of_measurement: hours

#################################################################
#                                                               #
#                        Shell Commmand                         #
#                                                               #
################################################################# 

shell_command:
  
#################################################################
#                                                               #
#                          Speed Test                           #
#                                                               #
################################################################# 
  
speedtestdotnet:
  server_id: 6106
  scan_interval:
    minutes: 30
  monitored_conditions:
    - ping
    - download
    - upload

#################################################################
#                                                               #
#                         System Health                         #
#                                                               #
################################################################# 

system_health:
